# Generated by Django 4.2.5 on 2023-09-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_food_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lizard',
            name='favorite_foods',
            field=models.ManyToManyField(to='main_app.food'),
        ),
    ]
